### ISSUE TITLE
Fix tilemap for mobiles

### ISSUE THREAD

**Issue by justgook** [justgook/webgl-playground#3]
Tilemap on mobiles behave not as expected try:
Use different format (bmp)
Check png sRGB param, and try different
Indexed png?

**Comment by justgook** [comment]
https://docs.unity3d.com/Manual/LinearRendering-LinearOrGammaWorkflow.html

Try to force gpu / image encoder create linear texture
1. Setting sRGB header to `3: Absolute colorimetric`
2. Gamma
...

**Comment by passiomatic** [comment]
I've prepared an Ellie that shows the issue on desktop too https://ellie-app.com/cz34CsLj83qa1 
It seems the first problematic index is 256.

![Schermata 2021-03-08 alle 11 51 47](https://user-images.githubusercontent.com/56371/110312120-fabf5600-8004-11eb-9397-ab50f0c64d95.png)
